exit when command fails in build/publish scripts

diff --git a/build/build b/build/build
--- a/build/build
+++ b/build/build
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+function handleErr {
+	SNAME=$(basename $BASH_SOURCE)
+	echo "$SNAME: Error on line $1"
+	exit 1
+}
+
+trap 'handleErr $LINENO' ERR
+
 # to minimize browser build, must have java 8+ installed, download
 # closure compiler, and set $CCJAR to the jar file's path.
 #  https://github.com/google/closure-compiler
diff --git a/build/publish b/build/publish
--- a/build/publish
+++ b/build/publish
@@ -1,6 +1,14 @@
 #!/bin/bash
 
 
+function handleErr {
+	SNAME=$(basename $BASH_SOURCE)
+	echo "$SNAME: Error on line $1"
+	exit 1
+}
+
+trap 'handleErr $LINENO' ERR
+
 
 # increment the version build number; awk must write to temp file
 awk -F '.' '{printf("%d.%d.%d",$1,$2,$3+1)}' version.txt > newver.txt
@@ -10,20 +18,14 @@ VERSION=`cat version.txt`
 
 ./build --publish
 
-if [ $? -ne 0 ]; then { echo "command failed" ; exit 1; } fi
-
 git add -A ../docs/
 git add version.txt
 git add -A browser/
 git add -A node/
 
-if [ $? -ne 0 ]; then { echo "command failed" ; exit 1; } fi
-
 git commit -m "build v$VERSION"
-
-if [ $? -ne 0 ]; then { echo "command failed" ; exit 1; } fi
 
 npm publish node
 
-echo published v$VERSION
+echo "published v$VERSION"
 
