build: more portable scripts, better versioning

diff --git a/build/publish b/build/publish
--- a/build/publish
+++ b/build/publish
@@ -1,69 +1,68 @@
 #!/bin/bash
 
-function handleErr {
-	SNAME=$(basename $BASH_SOURCE)
-	echo "$SNAME: Error on line $1"
-	exit 1
+handleErr() {
+	echo "$(basename "$BASH_SOURCE"): Error on line $1" >&2; exit 1
 }
-
 trap 'handleErr $LINENO' ERR
 
 
-function testDeps {
-	for i in "$@"; do $i --version > /dev/null 2>&1 || { echo "error: $i must be installed"; exit 1; } ; done
+testDeps() {
+	for i in "$@"; do $i --version > /dev/null 2>&1 || { echo "error: $i must be installed" >&2; exit 1; } ; done
 }
+
+# args: user, token, repo, releaseid, filename
+uploadAsset() {
+	echo "uploading $(basename "$5")"
+	curl -s -S -u "$1:$2" -H "Content-Type: application/octet-stream" --data-binary @"$5" "https://uploads.github.com/repos/$1/$3/releases/$4/assets?name=$(basename "$5")" > /dev/null
+}
+
+
 
 # make sure dependencies are installed
 testDeps git jq curl npm
 
 
 GHUSER="opatomic"
-GHREPO=`basename $(dirname $PWD)`
-if [[ -z "$GHTOKEN" ]]; then
-	if [[ -z "$GHTOKENFILE" ]]; then
-		GHTOKENFILE="$HOME/githubtoken"
-	fi
+GHREPO=$(basename "$(dirname "$PWD")")
+if [ -z "$GHTOKEN" ]; then
+	GHTOKENFILE="${GHTOKENFILE:-$HOME/githubtoken}"
 	if [ ! -f "$GHTOKENFILE" ]; then
 		echo "GHTOKEN or GHTOKENFILE must be set properly"
 		exit 1
 	fi
-	GHTOKEN=`cat $GHTOKENFILE`
+	GHTOKEN=$(cat "$GHTOKENFILE")
 fi
 
+[ "$(git rev-parse --is-inside-work-tree)" = "true" ] || (echo "error: not in git repo?" >&2; exit 1)
 
-MODCNT=`git status --porcelain | wc -l`
-if [ $MODCNT -ne 0 ]; then
-	echo "There are $MODCNT changes. Must revert or check in changes."
-	exit 1
+if [ "$PWD" != "$(git rev-parse --show-toplevel)/build" ]; then
+	echo "error: running from wrong directory?" >&2; exit 1
 fi
 
-VERSION=`cat version.txt`
-
-RELID=`curl -s -S "https://api.github.com/repos/$GHUSER/$GHREPO/releases/tags/v$VERSION" | jq ".id"`
-if [ $RELID != "null" ]; then
-	echo "github release v$VERSION already exists"
-	exit 1
+MODCNT=$(git status --porcelain | wc -l)
+if [ "$MODCNT" -ne 0 ]; then
+	echo "error: There are $MODCNT changes. Must revert or check in changes." >&2; exit 1
 fi
 
-VERSION="v$VERSION" ./build
+VERSION=$(./verget)
 
-
-# args: user, token, repo, releaseid, filename
-function uploadAsset {
-	echo "uploading $(basename $5)"
-	local UPLOADURL="https://uploads.github.com/repos/$1/$3/releases/$4/assets?name=$(basename $5)"
-	curl -s -S -u "$1:$2" -H "Content-Type: application/octet-stream" --data-binary @"$5" $UPLOADURL > /dev/null
-}
+if [ "v$VERSION" != "$(git describe --exact-match --tags HEAD)" ]; then
+	echo "error: source is not clean copy of tagged version" >&2; exit 1
+fi
 
 GHTAG="v$VERSION"
+GHRELID=$(curl -s -S "https://api.github.com/repos/$GHUSER/$GHREPO/releases/tags/$GHTAG" | jq ".id")
+if [ "$GHRELID" = "null" ]; then
+	echo "creating github release $GHTAG"
+	GHRELID=$(curl -s -S -u "$GHUSER:$GHTOKEN" -X POST "https://api.github.com/repos/$GHUSER/$GHREPO/releases" -d "{\"tag_name\":\"$GHTAG\"}" | jq ".id")
+fi
 
-# create release and get its id
-echo "creating release $GHTAG"
-GHRELID=`curl -s -S -u "$GHUSER:$GHTOKEN" -X POST "https://api.github.com/repos/$GHUSER/$GHREPO/releases" -d "{\"tag_name\":\"$GHTAG\"}" | jq ".id"`
+./build
+
 
 # upload files
-uploadAsset $GHUSER $GHTOKEN $GHREPO $GHRELID "out/opac.browser.js"
-uploadAsset $GHUSER $GHTOKEN $GHREPO $GHRELID "out/opac.browser.min.js"
+uploadAsset "$GHUSER" "$GHTOKEN" "$GHREPO" "$GHRELID" "out/opac.browser.js"
+uploadAsset "$GHUSER" "$GHTOKEN" "$GHREPO" "$GHRELID" "out/opac.browser.min.js"
 
 
 npm publish out/node
